[package]
name = "imagen"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
color-eyre = "0.6.5"
img = {path ="../img"}
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = "0.3.20"
