[package]
name = "img"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crc32fast = "1.5.0"
flate2 = "1.1.5"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = "0.3.20"
